enum ActionID {
    EVENT_ACTION_MOUSE_DOWN,

    WEEKLY_CAL__SWITCH_WEEK,
    
    WEEKLY_CAL__MOUSE_DOWN,
    WEEKLY_CAL__MOUSE_UP,
    WEEKLY_CAL__MOUSE_OVER,

    WEEKLY_CAL__PROPS_WEEK_START_TIME,
    WEEKLY_CAL__PROPS_HOURS_DAY_LENGTH,
    WEEKLY_CAL__PROPS_NODES_PER_HOUR,
    WEEKLY_CAL__PROPS_START_DAY_MILIS,

    AUTHENTICATION_LOG_IN,
    /*remove AUTHENTICATION_FAILED and AUTHENTICATION_SUCCEED - replace with Promise*/
    AUTHENTICATION_FAILED,
    AUTHENTICATION_SUCCEED,
    AUTHENTICATION_LOG_OUT
}

export { ActionID }