enum ActionID {
    WEEKLY_CAL__SWITCH_WEEK = 0,
    
    WEEKLY_CAL__MOUSE_DOWN,
    WEEKLY_CAL__MOUSE_UP,
    WEEKLY_CAL__MOUSE_OVER,

    WEEKLY_CAL__PROPS_WEEK_START_TIME,
    WEEKLY_CAL__PROPS_HOURS_DAY_LENGTH,
    WEEKLY_CAL__PROPS_NODES_PER_HOUR,
    WEEKLY_CAL__PROPS_START_DAY_MILIS
}

export { ActionID }